[package]
name = "rsy40"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
panic = "abort"
lto = true
codegen-units = 1

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
lazy_static = "1.4.0"
sqlite = "0.30.3"