name: release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Install rust
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          profile: minimal
#
#      - name: Build debug
#        uses: actions-rs/cargo@v1
#        with:
#          command: build
#
#      - name: Test
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
  deploy:
    name: deploy
#    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, x86_64-unknown-linux-gnu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: create dir
        run: |
          mkdir release
          mkdir release/${{ matrix.target }}
          touch release/${{ matrix.target }}/rsy40

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rsy40
          path: rsy40/${{ matrix.target }}
          retention-days: 5
